openapi: 3.0.0

info: 
  title: Event API
  description: API quản lý danh sách Event
  version: 1.0.0

servers: 
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/yuu-e71/event-api/1.0.0
  - url: http://localhost:3000/api
    description: Local server

paths:
  /events:
    get:
      summary: Lấy danh sách Event
      description: Trả về danh sách tất cả Event
      operationId: getAllListEvent
      tags: 
        - Event
      parameters:
        - name: page
          in: query
          required: false
          schema: 
            type: integer
            minimum: 1
          description: Trang hiện tại (Mặc định là 1)
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
          description: Số lượng Event trên mỗi trang (Mặc định là 10)
      responses:
        '200':
          description: Danh sách Event được trả về thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Lấy danh sách thành công
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Event'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /events/{id}:
    get:
      summary: Lấy chi tiết Event theo ID
      description: Trả về chi tiết Event theo ID
      operationId: getEventById
      tags: 
        - Event
      parameters:
        - name: id
          in: path
          required: true
          description: ID của Event
          schema: 
            type: string
      responses:
        '200':
          description: Lấy Event theo ID thành công
          content:
            application/json: 
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Lấy chi tiết Event theo ID thành công
                  data:
                    $ref: '#/components/schemas/Event'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500': 
          $ref: '#/components/responses/InternalServerError'

components:
  schemas:
    Event:
      type: object
      properties:
        event_id:
          type: number
          description: ID duy nhất của sự kiện.
          example: 2
        ten_events:
          type: string
          description: Tên đầy đủ của sự kiện.
          example: "The Future of Fundraising in Vietnam"
        slug:
          type: string
          description: Chuỗi thân thiện với URL (slug) của sự kiện, được tạo từ tên sự kiện.
          example: "the-future-of-fundraising-in-vietnam"
        host:
          type: string
          description: Tên của người hoặc tổ chức chủ trì sự kiện.
          example: "Mark Dickens"
        community_member_id:
          type: number
          description: ID của thành viên cộng đồng đã tạo hoặc quản lý sự kiện.
          example: 1
        in_person_location:
          type: string
          description: Địa điểm vật lý diễn ra sự kiện, nếu có.
          example: "1 Lê Thánh Tôn, Q1, HCM"
        starts_at:
          type: string
          format: date-time
          description: Thời gian bắt đầu của sự kiện (định dạng ISO 8601).
          example: "2025-05-07T18:00:00.000Z"
        ends_at:
          type: string
          format: date-time
          description: Thời gian kết thúc của sự kiện (định dạng ISO 8601).
          example: "2025-05-07T21:30:00.000Z"
        created_at:
          type: string
          format: date-time
          description: Thời gian sự kiện được tạo trong hệ thống (định dạng ISO 8601).
          example: "2025-06-04T17:36:48.000Z"
        updated_at:
          type: string
          format: date-time
          description: Thời gian lần cuối thông tin sự kiện được cập nhật (định dạng ISO 8601).
          example: "2025-06-04T09:36:48.000Z"
        url:
          type: string
          description: URL của trang sự kiện hoặc trang chi tiết trên nền tảng.
          example: "https://via-staging.circle.so/c/fundraising-space/the-future-of-fundraising-in-vietnam"
        cover_image_url:
          type: string
          description: URL của hình ảnh bìa hoặc đại diện cho sự kiện.
          example: "https://assets-v2.circle.so/tpes0cqsre18hcwvq3ct1159k7m3"
        description:
          type: string
          description: Mô tả chi tiết về sự kiện, bao gồm nội dung, mục tiêu và các thông tin liên quan khác.
          example: "Vietnam's startup ecosystem is rapidly evolving, drawing increased attention from both local and international investors..."
        price:
          type: string
          description: Giá vé tham dự sự kiện. Có thể là số tiền cụ thể hoặc chuỗi như "Miễn phí".
          example: "Miễn phí"
        max_attendees:
          type: number
          description: Số lượng người tham dự tối đa mà sự kiện có thể chứa.
          example: 100
        current_attendees:
          type: number
          description: Số lượng người tham dự hiện tại đã đăng ký hoặc check-in.
          example: 45
        status:
          type: string
          description: Trạng thái hiện tại của sự kiện.
          example: "upcoming"
        category:
          type: string
          description: Danh mục hoặc loại hình của sự kiện.
          example: "Networking"
        location_URL:
          type: string
          description: URL bản đồ hoặc đường dẫn đến địa điểm trực tuyến của sự kiện (nếu có).
          example: "https://goo.gl/maps/1LThanhTonQ1HCM"

  responses:
    BadRequest:
      description: Dữ liệu không hợp lệ
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: integer
                example: 400
              message:
                type: string
                example: ID không hợp lệ

    NotFound:
      description: Không tìm thấy tài nguyên
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: integer
                example: 404
              message:
                type: string
                example: Event không tồn tại

    InternalServerError:
      description: Có lỗi xảy ra trên server
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: integer
                example: 500
              message:
                type: string
                example: Có lỗi xảy ra trên server
