openapi: 3.0.0

info: 
  title: Event API
  description: API quản lý danh sách Event
  version: 1.0.0

servers: 
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/yuu-e71/event-api/1.0.0
  - url: http://localhost:3000/api
    description: Local server

paths:
  /events:
    get:
      summary: Lấy danh sách Event
      description: Trả về danh sách tất cả Event
      operationId: getAllListEvent
      tags: 
        - Event
      parameters:
        - name: page
          in: query
          required: false
          schema: 
            type: integer
            minimum: 1
          description: Trang hiện tại (Mặc định là 1)
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
          description: Số lượng Event trên mỗi trang (Mặc định là 10)
      responses:
        '200':
          description: Danh sách Event được trả về thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Lấy danh sách thành công
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Event'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /events/{id}:
    get:
      summary: Lấy chi tiết Event theo ID
      description: Trả về chi tiết Event theo ID
      operationId: getEventById
      tags: 
        - Event
      parameters:
        - name: id
          in: path
          required: true
          description: ID của Event
          schema: 
            type: string
      responses:
        '200':
          description: Lấy Event theo ID thành công
          content:
            application/json: 
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Lấy chi tiết Event theo ID thành công
                  data:
                    $ref: '#/components/schemas/Event'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500': 
          $ref: '#/components/responses/InternalServerError'

components:
  schemas:
    Event:
      type: object
      properties:
        id: 
          type: string
          example: "event1"
        name: 
          type: string
          example: "Event cosplay"
        slug:
          type: string
          example: "event-cosplay"
        host:
          type: string
          example: "Yuu"
        community_member_id:
          type: string
          example: 7a4e2b3f-cc3d-4f2c-90ab-23a5f01b9a78
        in_person_location:
          type: string
          example: Trung tâm hội chợ triễn lãm Sài Gòn SECC, quận 7
        starts_at: 
          type: string
          format: date
          example: "2025-05-24"
        ends_at:
          type: string
          format: date
          example: "2025-05-25"
        created_at:
          type: string
          format: date
          example: "2025-05-24"
        updated_at:
          type: string
          format: date
          example: "2025-05-24"
        url: 
          type: string
          example: "https://su-kien/event-cosplay"
        cover_image_url:
          type: string
          example: "https://images/events/event-cosplay-cover.jpg"
        description: 
          type: string
          example: "Event Cosplay năm 2025..."
        price: 
          type: number
          example: 250000
        max_attendees:
          type: number
          example: 300
        current_attendees: 
          type: number
          example: 150
        status: 
          type: string
          example: "upcoming"
        category: 
          type: string
          example: "Cosplay"
        location_URL:
          type: string
          example: "https://www.google.com/maps/place/Ho+Chi+Minh+City/@10.762622,106.660172,15z"

  responses:
    BadRequest:
      description: Dữ liệu không hợp lệ
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: integer
                example: 400
              message:
                type: string
                example: ID không hợp lệ

    NotFound:
      description: Không tìm thấy tài nguyên
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: integer
                example: 404
              message:
                type: string
                example: Event không tồn tại

    InternalServerError:
      description: Có lỗi xảy ra trên server
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: integer
                example: 500
              message:
                type: string
                example: Có lỗi xảy ra trên server
