import mongoose from 'mongoose';
import Event from './models/Event.model.js';

const sampleEvents = [
  {
    id: "event1",
    name: "Vietnam Gameverse 2025",
    slug: "vietnam-gameverse-2025",
    host: "Gameverse Org",
    community_member_id: "7a4e2b3f-cc3d-4f2c-90ab-23a5f01b9a78",
    in_person_location: "SECC, Quận 7",
    starts_at: new Date("2025-05-24"),
    ends_at: new Date("2025-05-25"),
    url: "https://su-kien/vietnam-gameverse-2025",
    cover_image_url: "https://example.com/images/event1.jpg",
    description: "Festival game lớn nhất Việt Nam 2025.",
    price: 250000,
    max_attendees: 500,
    current_attendees: 120,
    status: "upcoming",
    category: "festival",
    location_URL: "https://goo.gl/maps/abc1"
  },
  {
    id: "event2",
    name: "Tech Day 2025",
    slug: "tech-day-2025",
    host: "FPT Software",
    community_member_id: "8b4e2b3f-cc3d-4f2c-90ab-23a5f01b9a79",
    in_person_location: "FPT Software Campus",
    starts_at: new Date("2025-06-10"),
    ends_at: new Date("2025-06-11"),
    url: "https://su-kien/tech-day-2025",
    cover_image_url: "https://example.com/images/event2.jpg",
    description: "Ngày hội công nghệ toàn quốc.",
    price: 0,
    max_attendees: 1000,
    current_attendees: 800,
    status: "upcoming",
    category: "talk",
    location_URL: "https://goo.gl/maps/abc2"
  },
  {
    id: "event3",
    name: "Startup Open Day",
    slug: "startup-open-day",
    host: "FTU Hà Nội",
    community_member_id: "9c4e2b3f-cc3d-4f2c-90ab-23a5f01b9a80",
    in_person_location: "FTU Hà Nội",
    starts_at: new Date("2025-07-05"),
    ends_at: new Date("2025-07-05"),
    url: "https://su-kien/startup-open-day",
    cover_image_url: "https://example.com/images/event3.jpg",
    description: "Giao lưu khởi nghiệp trẻ.",
    price: 100000,
    max_attendees: 300,
    current_attendees: 150,
    status: "upcoming",
    category: "networking",
    location_URL: "https://goo.gl/maps/abc3"
  },
  {
    id: "event4",
    name: "AI Hackathon 2025",
    slug: "ai-hackathon-2025",
    host: "BKAI",
    community_member_id: "1d4e2b3f-cc3d-4f2c-90ab-23a5f01b9a81",
    in_person_location: "ĐH Bách Khoa TP.HCM",
    starts_at: new Date("2025-08-15"),
    ends_at: new Date("2025-08-17"),
    url: "https://su-kien/ai-hackathon-2025",
    cover_image_url: "https://example.com/images/event4.jpg",
    description: "Cuộc thi lập trình AI toàn quốc.",
    price: 0,
    max_attendees: 200,
    current_attendees: 80,
    status: "upcoming",
    category: "hackathon",
    location_URL: "https://goo.gl/maps/abc4"
  },
  {
    id: "event5",
    name: "Developer Conference VN",
    slug: "developer-conference-vn",
    host: "DevConf",
    community_member_id: "2e4e2b3f-cc3d-4f2c-90ab-23a5f01b9a82",
    in_person_location: "NCC Hanoi",
    starts_at: new Date("2025-09-20"),
    ends_at: new Date("2025-09-21"),
    url: "https://su-kien/developer-conference-vn",
    cover_image_url: "https://example.com/images/event5.jpg",
    description: "Hội nghị lập trình viên toàn quốc.",
    price: 300000,
    max_attendees: 600,
    current_attendees: 350,
    status: "upcoming",
    category: "conference",
    location_URL: "https://goo.gl/maps/abc5"
  },
  {
    id: "event6",
    name: "Cosplay Festival 2025",
    slug: "cosplay-festival-2025",
    host: "Cosplay Club",
    community_member_id: "3f4e2b3f-cc3d-4f2c-90ab-23a5f01b9a83",
    in_person_location: "Nhà Văn Hóa Thanh Niên",
    starts_at: new Date("2025-10-10"),
    ends_at: new Date("2025-10-11"),
    url: "https://su-kien/cosplay-festival-2025",
    cover_image_url: "https://example.com/images/event6.jpg",
    description: "Lễ hội cosplay lớn nhất năm.",
    price: 120000,
    max_attendees: 400,
    current_attendees: 200,
    status: "upcoming",
    category: "cosplay",
    location_URL: "https://goo.gl/maps/abc6"
  },
  {
    id: "event7",
    name: "Yoga Retreat 2025",
    slug: "yoga-retreat-2025",
    host: "Yoga Life",
    community_member_id: "4g4e2b3f-cc3d-4f2c-90ab-23a5f01b9a84",
    in_person_location: "Đà Lạt",
    starts_at: new Date("2025-11-05"),
    ends_at: new Date("2025-11-07"),
    url: "https://su-kien/yoga-retreat-2025",
    cover_image_url: "https://example.com/images/event7.jpg",
    description: "Chương trình yoga nghỉ dưỡng.",
    price: 500000,
    max_attendees: 100,
    current_attendees: 60,
    status: "upcoming",
    category: "yoga",
    location_URL: "https://goo.gl/maps/abc7"
  },
  {
    id: "event8",
    name: "Blockchain Summit 2025",
    slug: "blockchain-summit-2025",
    host: "Blockchain Assoc",
    community_member_id: "5h4e2b3f-cc3d-4f2c-90ab-23a5f01b9a85",
    in_person_location: "Gem Center",
    starts_at: new Date("2025-12-01"),
    ends_at: new Date("2025-12-02"),
    url: "https://su-kien/blockchain-summit-2025",
    cover_image_url: "https://example.com/images/event8.jpg",
    description: "Hội nghị Blockchain Việt Nam.",
    price: 400000,
    max_attendees: 350,
    current_attendees: 200,
    status: "upcoming",
    category: "summit",
    location_URL: "https://goo.gl/maps/abc8"
  },
  {
    id: "event9",
    name: "Women in Tech 2025",
    slug: "women-in-tech-2025",
    host: "WomenTech",
    community_member_id: "6i4e2b3f-cc3d-4f2c-90ab-23a5f01b9a86",
    in_person_location: "RMIT HCM",
    starts_at: new Date("2025-12-15"),
    ends_at: new Date("2025-12-15"),
    url: "https://su-kien/women-in-tech-2025",
    cover_image_url: "https://example.com/images/event9.jpg",
    description: "Sự kiện dành cho nữ giới trong ngành công nghệ.",
    price: 0,
    max_attendees: 250,
    current_attendees: 180,
    status: "upcoming",
    category: "talk",
    location_URL: "https://goo.gl/maps/abc9"
  },
  {
    id: "event10",
    name: "Networking Night 2025",
    slug: "networking-night-2025",
    host: "BizNet",
    community_member_id: "7j4e2b3f-cc3d-4f2c-90ab-23a5f01b9a87",
    in_person_location: "The Reverie Saigon",
    starts_at: new Date("2025-12-20"),
    ends_at: new Date("2025-12-20"),
    url: "https://su-kien/networking-night-2025",
    cover_image_url: "https://example.com/images/event10.jpg",
    description: "Đêm giao lưu kết nối doanh nghiệp.",
    price: 200000,
    max_attendees: 150,
    current_attendees: 90,
    status: "upcoming",
    category: "networking",
    location_URL: "https://goo.gl/maps/abc10"
  },
  {
    id: "event11",
    name: "Open Source Day 2025",
    slug: "open-source-day-2025",
    host: "OpenVN",
    community_member_id: "8k4e2b3f-cc3d-4f2c-90ab-23a5f01b9a88",
    in_person_location: "Hội trường Đại học CNTT",
    starts_at: new Date("2025-12-22"),
    ends_at: new Date("2025-12-22"),
    url: "https://su-kien/open-source-day-2025",
    cover_image_url: "https://example.com/images/event11.jpg",
    description: "Ngày hội phần mềm nguồn mở Việt Nam.",
    price: 0,
    max_attendees: 400,
    current_attendees: 210,
    status: "upcoming",
    category: "conference",
    location_URL: "https://goo.gl/maps/abc11"
  },
  {
    id: "event12",
    name: "Startup Pitching 2025",
    slug: "startup-pitching-2025",
    host: "Startup Hub",
    community_member_id: "9l4e2b3f-cc3d-4f2c-90ab-23a5f01b9a89",
    in_person_location: "Saigon Innovation Hub",
    starts_at: new Date("2025-12-25"),
    ends_at: new Date("2025-12-25"),
    url: "https://su-kien/startup-pitching-2025",
    cover_image_url: "https://example.com/images/event12.jpg",
    description: "Sân chơi gọi vốn cho startup trẻ.",
    price: 50000,
    max_attendees: 200,
    current_attendees: 120,
    status: "upcoming",
    category: "networking",
    location_URL: "https://goo.gl/maps/abc12"
  },
  {
    id: "event13",
    name: "Agile Vietnam 2025",
    slug: "agile-vietnam-2025",
    host: "Agile Vietnam",
    community_member_id: "0m4e2b3f-cc3d-4f2c-90ab-23a5f01b9a90",
    in_person_location: "Grand Plaza Hanoi",
    starts_at: new Date("2025-12-28"),
    ends_at: new Date("2025-12-29"),
    url: "https://su-kien/agile-vietnam-2025",
    cover_image_url: "https://example.com/images/event13.jpg",
    description: "Hội thảo Agile lớn nhất Việt Nam.",
    price: 150000,
    max_attendees: 350,
    current_attendees: 200,
    status: "upcoming",
    category: "workshop",
    location_URL: "https://goo.gl/maps/abc13"
  },
  {
    id: "event14",
    name: "Design Thinking Bootcamp",
    slug: "design-thinking-bootcamp",
    host: "DesignLab",
    community_member_id: "1n4e2b3f-cc3d-4f2c-90ab-23a5f01b9a91",
    in_person_location: "Innovation Lab HCM",
    starts_at: new Date("2026-01-05"),
    ends_at: new Date("2026-01-07"),
    url: "https://su-kien/design-thinking-bootcamp",
    cover_image_url: "https://example.com/images/event14.jpg",
    description: "Bootcamp về tư duy thiết kế sáng tạo.",
    price: 350000,
    max_attendees: 120,
    current_attendees: 80,
    status: "upcoming",
    category: "workshop",
    location_URL: "https://goo.gl/maps/abc14"
  }
];

mongoose.connect('mongodb+srv://dbEvent:admin123@cluster0.bg84pcc.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0')
  .then(async () => {
    console.log("✅ Đã kết nối MongoDB");

    await Event.deleteMany();
    console.log("🗑️ Đã xoá dữ liệu cũ");

    try {
      await Event.insertMany(sampleEvents, { ordered: false });
      console.log("✅ Đã thêm 10 sự kiện mẫu vào MongoDB");
    } catch (error) {
      console.error("❌ Lỗi khi thêm một số sự kiện:", error);
    }

    mongoose.disconnect();
  })
  .catch((err) => {
    console.error("❌ Lỗi kết nối MongoDB:", err);
  });
